// Alert trigger type identifiers shared across the AlertsManager modules.
const TRIGGERS = {
  CLIENT_OFFLINE: 'CLIENT_OFFLINE',
  CLIENT_DEGRADED: 'CLIENT_DEGRADED',
  CLIENT_ONLINE: 'CLIENT_ONLINE',
  SCRIPT_EXECUTION_FAILED: 'SCRIPT_EXECUTION_FAILED',
  USB_DEVICE_CONNECTED: 'USB_DEVICE_CONNECTED',
  USB_DEVICE_DISCONNECTED: 'USB_DEVICE_DISCONNECTED',
  CRITICAL_USB_DEVICE_CONNECTED: 'CRITICAL_USB_DEVICE_CONNECTED',
  CRITICAL_USB_DEVICE_DISCONNECTED: 'CRITICAL_USB_DEVICE_DISCONNECTED',
};

module.exports = {
  TRIGGERS,
};
